### ISSUE TITLE
dill required

### ISSUE THREAD

**Issue by fmetze** [srvk/DiViMe#10] opened 2018-08-11 22:35 UTC
When running the tutorial (processing cough.wav), I needed to "pip install dill" before the example would run sucessfully.

**Comment by riebling** [comment] 2018-08-14 18:44
Interesting. Dill is installed at Vagrant provision time, but in an anaconda Python virtualenv. So running the command from external to the VM, I bet the prefixing of anaconda/ to the PATH is missing, and can be fixed by incorporating that into the run script.

**Comment by jukaradayi** [comment] 2018-08-14 18:57
Has this been resolved?

**Comment by riebling** [comment] 2018-08-14 19:28
in progress! what confuses me is when I look at the latest `Vagrantfile` and `runClasses.sh` they have this fix already. If you're running an older instantiation of DiViMe, or one from ACLEW and not the one from SRVK GitHub repository, this could be why.

[Vagrantfile](https://github.com/srvk/DiViMe/blob/master/Vagrantfile) line 240:
```
    su ${user} -c "/home/${user}/anaconda/bin/conda install numpy scipy mkl dill tabulate joblib"
```
[OpenSAT](https://github.com/srvk/OpenSAT/blob/master/runClasses.sh) line 21:
```
export PATH=/home/${USER}/anaconda/bin:$PATH
```

**Comment by riebling** [comment] 2018-08-14 19:32
Oops I see why. USER is still not the right way to get the machine's default user, and the bug is insidious!  It makes a difference how you run the command from outside the VM, whether you use single or double quotation marks!!! An expert such as us might not even notice because we are so used to quoting commands!

Notice the difference:
```
Gandalf:DiViMe macw$ vagrant ssh -c 'echo $USER'
vagrant
Connection to 127.0.0.1 closed.
Gandalf:DiViMe macw$ vagrant ssh -c "echo $USER"
macw
Connection to 127.0.0.1 closed.
```

**Comment by riebling** [comment] 2018-08-14 19:46
See if this change to the [Tutorial](https://github.com/srvk/DiViMe/wiki/Tutorial) fixes this issue - substituting single quotes, so that `$USER` gets dereferenced by the VM, not the host machine

**Comment by riebling** [comment] 2018-08-14 20:29
can't reproduce :-/ 
```
history
  501  cd DiViMe/
  502  git pull
  503  vagrant destroy
  504  vagrant up
  505  fg
  506  grep dill Vagrantfile
  507  vagrant status
  508  vagrant ssh -c 'OpenSAT/runClasses.sh /vagrant/data'

...

er1k@islpc22:/usr1/er1k/boxes/DiViMe$ vagrant ssh -c 'OpenSAT/runClasses.sh /vagrant/data'
Extracting features for cough.wav ...
(MSG) [2] in SMILExtract : openSMILE starting!
(MSG) [2] in SMILExtract : config file is: /vagrant/MED_2s_100ms_htk.conf
(MSG) [2] in cComponentManager : successfully registered 95 component types.
(MSG) [2] in cComponentManager : successfully finished createInstances
                                 (19 component instances were finalised, 1 data memories were finalised)
(MSG) [2] in cComponentManager : starting single thread processing loop
(MSG) [2] in cComponentManager : Processing finished! System ran for 1721 ticks.
DONE!
Loading neural network...
Filename cough.htk
Predicting for cough ...
Connection to 127.0.0.1 closed.
er1k@islpc22:/usr1/er1k/boxes/DiViMe$ cat data/hyp/cough.rttm 
SPEAKER	cough	1	0.0	0.0	music_sing  	<NA>	<NA>	0.367768079042
SPEAKER	cough	1	0.0	0.1	crowd        	<NA>	<NA>	0.419847130775
SPEAKER	cough	1	0.1	0.3	music_sing  	<NA>	<NA>	0.375354379416
SPEAKER	cough	1	0.4	0.8	music       	<NA>	<NA>	0.285134375095
SPEAKER	cough	1	1.2	1.5	background  	<NA>	<NA>	0.178366959095
SPEAKER	cough	1	2.7	0.5	music       	<NA>	<NA>	0.230460226536
SPEAKER	cough	1	3.2	0.2	background  	<NA>	<NA>	0.245576620102
SPEAKER	cough	1	3.4	0.4	music       	<NA>	<NA>	0.237979069352
SPEAKER	cough	1	3.8	0.1	music_sing  	<NA>	<NA>	0.253297328949
SPEAKER	cough	1	3.9	0.8	music       	<NA>	<NA>	0.307353198528
SPEAKER	cough	1	4.7	1.1	crowd        	<NA>	<NA>	0.279803872108
SPEAKER	cough	1	5.8	5.4	music_sing  	<NA>	<NA>	0.282180398703
SPEAKER	cough	1	11.2	1.1	music       	<NA>	<NA>	0.302925169468
SPEAKER	cough	1	12.3	4.0	background  	<NA>	<NA>	0.486689478159
```

**Comment by fmetze** [comment] 2018-08-15 10:36
No, it breaks for me if I do not explicitly list dill. In your test, is dill listed in the packages that get installed in the Anaconda environment?

If I do not explicitly list dill, it does not get installed during

    default: Downloading Anaconda-2.3.0...
    default: Installing Anaconda-2.3.0...
    default: PREFIX=/home/vagrant/anaconda
    default: installing: python-2.7.10-0 ...
    [...]
    default: installing: _cache-0.0-x0 ...
    default: Python 2.7.10 :: Continuum Analytics, Inc.
    default: creating default environment...
    default: installation finished.

**Comment by jukaradayi** [comment] 2018-08-15 14:04
I installed a new DiViMe system on mac and I am not able to reproduce this error either.
`MacBook-Pro-de-Ewan:DiViMe bootphon$ vagrant ssh -c '/home/vagrant/anaconda/bin/pip freeze'
[...]
dill==0.2.8.2
[...]`

Could you please launch the same command `vagrant ssh -c '/home/vagrant/anaconda/bin/pip freeze'` after creating the VM and copy the output ? Thank you !

**Comment by fmetze** [comment] 2018-08-15 22:11
I am very confused now - I installed a new system, adding dill to the list of packages, and now it does not even find numpy, but numpy (and dill) seem to be installed:

Florians-MacBook-Pro:DiViMe-2 metze$ vagrant ssh -c "tools/yunitate.sh data/"
wavs and transcriptions found !
Tests finished
Starting
Extracting features for test.wav ...
(MSG) [2] in SMILExtract : openSMILE starting!
(MSG) [2] in SMILExtract : config file is: /vagrant/MED_2s_100ms_htk.conf
(MSG) [2] in cComponentManager : successfully registered 95 component types.
(MSG) [2] in cComponentManager : successfully finished createInstances
                                 (19 component instances were finalised, 1 data memories were finalised)
(MSG) [2] in cComponentManager : starting single thread processing loop
(MSG) [2] in cComponentManager : Processing finished! System ran for 168 ticks.
DONE!
Traceback (most recent call last):
  File "diarize.py", line 3, in <module>
    from fileutils.htk import *
  File "/home/vagrant/G/coconut/fileutils/htk.py", line 1, in <module>
    import numpy
ImportError: No module named numpy
sort: cannot read: /vagrant/data/Yunitemp/test.rttm.sorted: No such file or directory
tools/yunitate.sh finished running
Connection to 127.0.0.1 closed.
Florians-MacBook-Pro:DiViMe-2 metze$ vagrant ssh -c '/home/vagrant/anaconda/bin/pip freeze'
abstract-rendering==0.5.1
alabaster==0.7.3
argcomplete==0.8.9
asn1crypto==0.22.0
astropy==1.0.3
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
bcolz==0.9.0
beautifulsoup4==4.3.2
binstar==0.11.0
bitarray==0.8.1
blaze==0.8.0
blz==0.6.2
bokeh==0.9.0
boto==2.38.0
Bottleneck==1.0.0
cdecimal==2.3
certifi==2018.8.13
cffi==1.10.0
clyent==0.3.4
colorama==0.3.3
conda==4.5.10
conda-build==1.14.1
configobj==5.0.6
cryptography==1.8.1
Cython==0.22.1
cytoolz==0.7.3
datashape==0.4.5
decorator==3.4.2
dill==0.2.8.2
docutils==0.12
enum34==1.1.6
fastcache==1.0.2
Flask==0.10.1
funcsigs==0.4
futures==3.2.0
gevent==1.0.1
gevent-websocket==0.9.3
greenlet==0.4.7
grin==1.2.1
h5py==2.5.0
idna==2.6
intervaltree==2.1.0
ipaddress==1.0.18
ipython==3.2.0
itsdangerous==0.24
jdcal==1.0
jedi==0.8.1
Jinja2==2.7.3
joblib==0.12.2
jsonschema==2.4.0
llvmlite==0.5.0
lxml==3.4.4
MarkupSafe==0.23
matplotlib==1.4.3
mistune==0.5.1
mkl-fft==1.0.4
mkl-random==1.0.1
mock==1.0.1
multipledispatch==0.4.7
networkx==1.9.1
nltk==3.0.3
nose==1.3.7
numba==0.19.1
numexpr==2.4.3
numpy==1.15.0
odo==0.3.2
openpyxl==1.8.5
packaging==16.8
pandas==0.16.2
patsy==0.3.0
pep8==1.6.2
Pillow==2.8.2
ply==3.6
psutil==2.2.1
ptyprocess==0.4
py==1.4.27
pyasn1==0.1.7
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.19.5.1
pyflakes==0.9.2
Pygments==2.0.2
pympi-ling==1.69
pyOpenSSL==17.0.0
pyparsing==2.2.0
pytest==2.7.1
python-dateutil==2.4.2
pytz==2015.4
PyYAML==3.11
pyzmq==14.7.0
redis==2.10.3
requests==2.14.2
rope==0.9.4
runipy==0.1.3
scikit-image==0.11.3
scikit-learn==0.16.1
scipy==1.1.0
six==1.10.0
snowballstemmer==1.2.0
sockjs-tornado==1.0.1
sortedcontainers==2.0.4
Sphinx==1.3.1
sphinx-rtd-theme==0.1.7
spyder==2.3.5.2
SQLAlchemy==1.0.5
statsmodels==0.6.1
sympy==0.7.6
tables==3.2.0
tabulate==0.8.2
terminado==0.5
tgt==1.4.3
Theano==0.8.2
toolz==0.7.2
tornado==4.2
ujson==1.33
unicodecsv==0.9.4
Werkzeug==0.10.4
xlrd==0.9.3
XlsxWriter==0.7.3
xlwt==1.0.0
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Connection to 127.0.0.1 closed.

**Comment by fmetze** [comment] 2018-08-15 23:02
Ok, the ~/.bashrc in the VM contains the following lines near the beginning:

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

If I comment them out, things work as expected (i.e. I have numpy and dill, and 'vagrant ssh -c "tools/yunitate.sh data"' works), if I leave them as-is, things break. Can you check what you have? Could there be a weird interdependence of settings on the host computer with the guest?

**Comment by riebling** [comment] 2018-08-16 15:06
Short answer: bizarre Vagrant bug.  `vagrant ssh` gives a login environment that picks up paths to anaconda (and with it, dill and friends), but `vagrant ssh -c <command>` seems to sometimes give login environment, sometimes not. (It's supposed to!)

Another answer: confusion on my part between the subtle differences between login environment (bash -l), interactive shell (bash -i), and .bashrc

According to a bug report from 2013, the default behavior of Vagrant changed from running without, to with a "login environment" (bash -l). 

It's now supposed to be configurable in `Vagrantfile` with:
```
config.ssh.shell - The shell to use when executing SSH commands from Vagrant. By default this is bash -l. Note that this has no effect on the shell you get when you run vagrant ssh. This configuration option only affects the shell to use when executing commands internally in Vagrant.
```
I tried setting this to "bash -l" to get a login environment but this didn't change the environment when running commands like `vagrant ssh -c 'env'`.  When I change it to "bash -i" then by default commands given as "vagrant ssh -c <command>" DO get an interactive login environment
```
er1k@islpc22:/usr1/er1k/boxes/DiViMe$ vagrant ssh -c "env | grep PATH"
PATH=/home/vagrant/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Connection to 127.0.0.1 closed.
```

This also explains why some of our scripts that used to `source .bashrc` to pick up paths for Python + Anaconda environment had that line commented out, and since then, we've been making scripts explicitly prepend `/home/${USER}/anaconda/bin` before running python things.

You managed to find a very sneaky Vagrant behavior!  Could others maybe share their Vagrant version here to see if that difference explains this behavior? (with `vagrant --version`)

EXAMPLES:
For Brian's Mac: Vagrant 2.1.2
On my workstation: Vagrant 2.0.3

This impacted our teammates' scripting earlier, and many others trying to use `vagrant ssh -c <command>` and expecting the login environment to be set.

**Comment by jukaradayi** [comment] 2018-08-17 14:03
I got back to my office in Paris and I can reproduce Florian's bug on my office-computer !
I'm using Vagrant 2.0.2 with virtualbox 5.1.38

**Comment by riebling** [comment] 2018-08-17 14:41
1) Does the Vagrantfile I updated correct this problem? (by making the default `vagrant ssh` use interactive login, thus setting the Anaconda + Python environment)
2) If you run the command by logging into the VM rather externally, does it then work OK (because the `vagrant ssh` is truly an interactive environment)

For 2) A quick check would be to do the following on a machine that 'doesn't work':
```
vagrant ssh
env | grep PATH
```
and test whether or not `/home/vagrant/anaconda/bin` is at the beginning of the PATH.

For 1) A slower check would be to `vagrant destroy` then `git pull` (and verify it gets a newer Vagrantfile) then try something like
```
vagrant ssh -c 'env | grep PATH`
```
and again see if `/home/vagrant/anaconda/bin` is at the beginning of the PATH

**Comment by jukaradayi** [comment] 2018-08-20 13:26
For 2., yes when I tried launching the tools from inside the VM (i.e. after a `vagrant ssh`), everything worked find and `/home/vagrant/anaconda/bin` appeared in the PATH.

For 1., I destroyed my VM, made a `git pull` and a `vagrant up` again, and yes, it fixed the problem ! 
Now, when I have the following (from outside of the VM):
`bootphon2018@bootphon2018-OptiPlex-7010:~/Workspace/usefulVM/DiViMe$ vagrant ssh -c 'env | grep PATH'
PATH=/home/vagrant/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Connection to 127.0.0.1 closed.
bootphon2018@bootphon2018-OptiPlex-7010:~/Workspace/usefulVM/DiViMe$ vagrant ssh -c "tools/yunitate.sh data/"
wavs and transcriptions found !
Tests finished
Starting
Extracting features for chunk_usb_3600.wav ...
(MSG) [2] in SMILExtract : openSMILE starting!
(MSG) [2] in SMILExtract : config file is: /vagrant/MED_2s_100ms_htk.conf
(MSG) [2] in cComponentManager : successfully registered 95 component types.
(MSG) [2] in cComponentManager : successfully finished createInstances
                                 (19 component instances were finalised, 1 data memories were finalised)
(MSG) [2] in cComponentManager : starting single thread processing loop
(MSG) [2] in cComponentManager : Processing finished! System ran for 1523 ticks.
DONE!
tools/yunitate.sh finished running
Connection to 127.0.0.1 closed.
`

**Comment by riebling** [comment] 2018-08-20 15:01
Great! maybe if this works for Florian, we can close this issue.

**Comment by riebling** [comment] 2018-08-29 19:42
Assuming if it works for Julien-reproducing-Florian, it works for others also on OSX

**Closed by riebling** 2018-08-29 19:42 UTC
