### ISSUE TITLE
DiViMe installation fail

### ISSUE THREAD

**Issue by NaomiHavron** [srvk/DiViMe#117] opened 2019-04-02 08:41 UTC

**Comment by NaomiHavron** [comment] 2019-04-02 08:43
When I try to install DiViMe this last step fails:

\DiViMe>vagrant ssh -c "launcher\test.sh"
launchertest.sh: command not found
Connection to 127.0.0.1 closed.

I tried destroying and reinstalling vagrant, Alex thought it might help you to figure out the problem if I post here the output of the consule when I do that, here it is:

https://docs.google.com/document/d/1gZtCsALKTuHeHpyYBmHA-d-vn6NeK8clftSiMi4VfkE/edit?usp=sharing

**Comment by NaomiHavron** [comment] 2019-04-02 08:44
Sorry, closed this my mistake (my first time opening an issue...)

**Comment by MarvinLvn** [comment] 2019-04-02 09:12
Hi Naomi !

There's just a mistake in your command, you must type : 

`vagrant ssh -c "launcher/test.sh"`

In UNIX path convention, each directories is separated by "**/**". If you type '"\", the system won't understand that you want to go through the directory **launcher**, and then execute the script **test.sh**

But the virtual machine has been designed  in such a way that you don't need to be aware of all of this complicated stuff. Just type : 

`vagrant ssh -c "test.sh"`

**Comment by MarvinLvn** [comment] 2019-04-02 11:31
Reopening the issue based on the google doc provided above.

I won't have time to fix this issue today, and I need my personal computer to install the VM on windows.
I'll keep you in touch as soon as the problem has been fixed!

**Comment by NaomiHavron** [comment] 2019-04-02 12:16
Yes, because  vagrant ssh -c "test.sh" doesn't work either

thanks!

**Comment by fmetze** [comment] 2019-04-02 13:55
can you change the “\” in “launcher\test.sh” to a “/“ so that it corresponds to a valid linux path? is the “\” referenced somewhere in the documentation? if so, please indicate where you found it, and we’ll change it.

**Comment by MarvinLvn** [comment] 2019-04-02 14:03
Even though the command for running the test script was wrong, it seems that she met some troubles during the installation, here's the relevant part of the google drive she sent to us : 

```
C:\Users\naomi\DiViMe>vagrant ssh -c "test.sh"
: No such file or directory
Connection to 127.0.0.1 closed.

C:\Users\naomi\DiViMe>vagrant ssh -c "launcher\test.sh"
launchertest.sh: command not found
Connection to 127.0.0.1 closed.

C:\Users\naomi\DiViMe>vagrant ssh -c "launcher/test.sh"
: No such file or directory
Connection to 127.0.0.1 closed.
```

The script **test.sh** seems to be missing from her VM.

**Comment by NaomiHavron** [comment] 2019-04-02 14:06
Neither of the slashes work, it's not about the slash...

**Comment by fmetze** [comment] 2019-04-02 14:34
What happens if you log into the VM interactively and do something like

vagrant ssh
ls -l
ls -l launcher
git status

or

vagrant ssh -c “ls -l”

**Comment by NaomiHavron** [comment] 2019-04-03 07:18
Hi,
This is what happens when I type that in the consule:

C:\Users\naomi\DiViMe>vagrant ssh -c "ls -l"
total 12
drwxr-xr-x 21 vagrant vagrant 4096 Apr  1 14:06 anaconda
-rwxr-xr-x  1 vagrant vagrant  491 Apr  1 13:26 environment.yml
lrwxrwxrwx  1 vagrant vagrant   17 Apr  1 14:10 launcher ->
/vagrant/launcher
drwxrwxr-x 10 vagrant vagrant 4096 Apr  1 14:09 repos
lrwxrwxrwx  1 vagrant vagrant   14 Apr  1 14:10 utils -> /vagrant/utils
Connection to 127.0.0.1 closed.

Best,
Naomi

**Comment by fmetze** [comment] 2019-04-03 13:17
I assume you are running this with Virtualbox under Windows? Or are you using Docker?

I assume that you have “launcher” and “utils” sub-folders in the Windows folder in which you start the VM?

If so (and using VirtualBox), can you change line 20 in the file “Vagrantfile” from

config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", :mount_options => ["dmode=777", "fmode=777”]

to

config.vm.synced_folder ".", "/vagrant", type: "smb"
and build the VM again? I don’t have a Windows host to test, unfortunately. My guess is that the host folder does not get mounted correctly. To help diagnose, please do 

vagrant ssh -c “ls -l launcher”

like I asked in yesterday’s email.

Thanks,

Florian

**Comment by NaomiHavron** [comment] 2019-04-05 08:31
Hello Florian,

As I wrote in the previous email, this is what happens when I type  vagrant
ssh -c “ls -l launcher”
in the consule (command line):

C:\Users\naomi\DiViMe>vagrant ssh -c "ls -l"
total 12
drwxr-xr-x 21 vagrant vagrant 4096 Apr  1 14:06 anaconda
-rwxr-xr-x  1 vagrant vagrant  491 Apr  1 13:26 environment.yml
lrwxrwxrwx  1 vagrant vagrant   17 Apr  1 14:10 launcher ->
/vagrant/launcher
drwxrwxr-x 10 vagrant vagrant 4096 Apr  1 14:09 repos
lrwxrwxrwx  1 vagrant vagrant   14 Apr  1 14:10 utils -> /vagrant/utils
Connection to 127.0.0.1 closed.

As for your instructions, I have never used a VM before, and it is unclear
to me how to execute the following line:
"If so (and using VirtualBox), can you change line 20 in the file
“Vagrantfile” from"

How do I use the VirtualBox to change a line of script?

Thanks for your help,
Naomi Havron, PhD.

**Comment by fmetze** [comment] 2019-04-05 13:18
Apologies, I could have been more clear. It is difficult to debug this entirely remotely, maybe you can get someone local to help you a bit with this, if things are unclear?

- “(and using Virtualbox)” was meant to say that I assume you are using Virtualbox on Windows to host the Virtual Machine? You should not try to use Virtualbox to edit the Vagrant file
- If you are indeed using Virtualbox to run the VM, then you should identify the Vagrantfile in the divime folder (you have probably used it to build the VM), and load it into the text editor of your choice, find line 20, edit it according to my suggestion, and rebuild the VM
- This will use a different mechanism to make the host’s file system visible inside the client (the VM), which seems to be the root cause of the issue that you are experiencing.
- Before and after making that change (i.e. in the current and the re-built VM), what is the output of 

	ssh -c “ls -l launcher"

Hope this helps!

Florian

**Comment by NaomiHavron** [comment] 2019-04-09 12:34
Hi Florian,

After I change line 20, the following error occurs:
C:\Users\naomi\DiViMe>vagrant ssh -c "ls -l launcher"
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

C:/Users/naomi/DiViMe/Vagrantfile:23: syntax error, unexpected tIDENTIFIER,
expecting ']'
    override.vm.box = "ubuntu/trusty64"
                             ^
C:/Users/naomi/DiViMe/Vagrantfile:23: syntax error, unexpected tSTRING_BEG,
expecting keyword_do or '{' or '('
ide.vm.box = "ubuntu/trusty64"
                              ^
C:/Users/naomi/DiViMe/Vagrantfile:30: syntax error, unexpected tIDENTIFIER,
expecting keyword_end
    config.ssh.shell = "bash -i"
                            ^
C:/Users/naomi/DiViMe/Vagrantfile:30: syntax error, unexpected tSTRING_BEG,
expecting keyword_do or '{' or '('
  config.ssh.shell = "bash -i"
                              ^
C:/Users/naomi/DiViMe/Vagrantfile:33: syntax error, unexpected tIDENTIFIER,
expecting keyword_end
ig.vm.network "private_network", ip: "192.168.56.101"
                              ^
C:/Users/naomi/DiViMe/Vagrantfile:33: unexpected fraction part after
numeric literal
private_network", ip: "192.168.56.101"
                              ^
C:/Users/naomi/DiViMe/Vagrantfile:33: syntax error, unexpected tFLOAT,
expecting end-of-input
ate_network", ip: "192.168.56.101"
                              ^
I should say that when I do vagrant up, the following is the end of the
message I get:

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Thank you for helping with this!
Naomi

**Comment by NaomiHavron** [comment] 2019-04-10 08:39
Windows version - Windows 10 Home, Version 1803
vagrant version - 2.2.4 x86_64
Virtualbox version - 5.2.18

Would it help if we set a time and I let you remotely control my machine?

Thanks again,
Naomi

**Comment by fmetze** [comment] 2019-04-10 13:18
My guess is that there is a syntax error in your Vagrantfile, in our near line 20. Can you please send your Vagrantfile? 

Maybe @MarvinLvn can help debug further? I do not have access to Windows Home machines here, and I don't think remote debugging is efficient.

**Comment by NaomiHavron** [comment] 2019-04-10 13:28
I attached it to my last email.
Here it is again in case you didn't get it.

**Comment by fmetze** [comment] 2019-04-10 13:33
I think attachments are ignored in e-mail replies to comments on Github. You need to attach the file in the web form.

**Comment by NaomiHavron** [comment] 2019-04-10 13:47
I hope you can see it now (I had to change the extension to txt, because github doesn't support this format)
[Vagrantfile.txt](https://github.com/srvk/DiViMe/files/3064098/Vagrantfile.txt)

**Comment by fmetze** [comment] 2019-04-10 15:18
This is the original Vagrantfile, which does not cause the problem during building, but only during running, right?

**Comment by NaomiHavron** [comment] 2019-04-10 15:27
Yes, I made a mistake there, I ran the wrong file - sorry about that.
This is the changes file:
[Vagrantfile.txt](https://github.com/srvk/DiViMe/files/3064534/Vagrantfile.txt)

When I run the vagrant up after changing line 20, then the cmd line reads:
C:\Users\naomi\DiViMe>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' version '20190318.0.0' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' for provider 'virtualbox' is
==> default: available! You currently have version '20190318.0.0'. The latest is version
==> default: '20190408.0.0'. Run `vagrant box update` to update.
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by fmetze** [comment] 2019-04-10 15:28
This part of the log file (the one you shared on Google drive) might be relevant:

    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.

Please update the guest additions in the VM and try again

**Comment by MarvinLvn** [comment] 2019-04-11 17:34
@fmetze @NaomiHavron 

I just installed the VM on Windows 10.
I also met the "**No such file or directory**" problem.
I SSH'ed in the VM, and everything looked perfectly normal : all the necessary files are in their right location, the content is OK, everything is perfect !

From within the VM, running the **test.sh** script returned the same **"No such file or directory"** error.
I found out that it was coming from a wrongly formatted shebang line.

To see the hidden characters : 

```
head -1 test.sh | od -c
```

whose output was :

```
0000000   #   !   /   b   i   n   /   b   a   s   h  \r  \n
```

The extra carriage at the end (**\r**) of the line produces the error.
I used vim to fix this issue with :

```
vi test.sh
:set ff=unix
:set nobomb
:wq
```

And then I was able to run **test.sh** !
The extra carriage seems to be present in all of the **.sh** files (therefore, all of them are broken).
We still need to know when (and by what) it has been imported to fix the issue.

Do you have any ideas @fmetze ? 

Bonus : A folder git issue that might be relevant https://github.com/aclew/DiViMe/issues/1

**Comment by fmetze** [comment] 2019-04-11 18:14
Interesting! When I look at test.sh in GitHub, I get:

Executable File  231 lines (189 sloc)  8.14 KB
Raw <https://github.com/srvk/DiViMe/raw/master/launcher/test.sh>Blame <https://github.com/srvk/DiViMe/blame/master/launcher/test.sh>History <https://github.com/srvk/DiViMe/commits/master/launcher/test.sh>

When I download the “raw” contents to my computer, I get

Florians-MacBook-Pro:Desktop metze$ ls -l test.sh 
-rw-r--r--@ 1 metze  staff  8333 Apr 11 14:07 test.sh
Florians-MacBook-Pro:Desktop metze$ head -n 1 test.sh | od -c
0000000    #   !   /   b   i   n   /   b   a   s   h      \n            
0000015

There is no “\r”, but a space at the end of the shebang.

Now, is it possible that when checking out DiViMe on a Windows machine, Git will convert this Unix-format script to a Windows-format script, which will fail when executed from within Linux? I thought it should still work - but maybe not.

Could you compare the length of the test.sh before and after your vim-treatment?

**Comment by MarvinLvn** [comment] 2019-04-12 15:20
I also thought about the git clone problem. I found an interesting link : https://github.com/Microsoft/WSL/issues/2318

I'll try the **.gitattribute** solution.

**Comment by MarvinLvn** [comment] 2019-04-16 22:06
Hello @NaomiHavron,

You should be able to install the VM now.
Please delete the DiViMe folder before following the installation instructions.

On a side note for developers : The solution was indeed to add  the ***.sh text eol=lf** line in **.gitattribute** to avoid git incoporating Windows-style line endings in **.sh** scripts.

I close the issue.

**Closed by MarvinLvn** 2019-04-16 22:06 UTC

**Comment by marisacasillas** [comment] 2019-07-15 07:59
@MarvinLvn @fmetze I still had this line ending issue w/ a clone on Windows 10 a few days ago. Is this something I need to set on my local git preferences or something? Or can you prevent the Windows line endings from being added on the srvk side?

**Comment by fmetze** [comment] 2019-07-15 11:56
i added a .gitattributes file in the repository, this should hopefully fix this issue

**Comment by marisacasillas** [comment] 2019-07-15 12:03
thanks! i'll sync and re-try in a few hours.
