### ISSUE TITLE
incorporate the yunitator Florian presented in BsAs into VM

### ISSUE THREAD

**Issue by jukaradayi** [srvk/DiViMe#14] opened 2018-08-14 19:01 UTC

**Comment by fmetze** [comment] 2018-08-14 21:46
possibly a duplicate of #16 if we train (on the new dataset) multiple Yunitator variants:
- silence vs primary child vs all other speech
- silence vs child vs male vs female (this is "the Yunitator that Florain presented in BsAs")
- a Yunitator with silence vs primary child vs other child vs male adult vs female adult (vs anything else?)

**Comment by alecristia** [comment] 2018-08-15 11:42
I would like to ask if the 3-class version you presented on Monday can be incorporated to the VM today, if possible. Better one code in hand than a hundred in the future! If this gets done, Julien could start documenting performance across all the clips we've been using for benchmarking.

Any other retraining or retrainable will be a good addition in the future, but the future is not now ;)

**Comment by fmetze** [comment] 2018-08-15 12:11
3-class means silence, child, father, mother - Eric?

**Comment by riebling** [comment] 2018-08-15 13:51
Yunitator produces these 3 classes (plus Silence):
```
CHI
FEM
MAL
SIL
```

Assuming the http://github.com/srvk/DiViMe/tools repository was installed, that should contain the run scripts to run Yunitator "in the DiViMe way" `tools/yunitate.sh` on a folder containing WAV data - typically `data/` in the host and `/vagrant/data` from the VM perspective. From outside the VM, the command would be:
```
vagrant ssh -c "tools/yunitate.sh data"
```
Output will be in the same (`data`) folder as files based on input filenames, such as `yunitator_test.rttm` `yunitator_AR31_021108a.rttm` etc. and would look like:
```
SPEAKER mark.rttm       1       0.0     0.9     <NA>    <NA>    FEM     <NA>    <NA>
SPEAKER mark.rttm       1       0.9     0.3     <NA>    <NA>    CHI     <NA>    <NA>
SPEAKER mark.rttm       1       1.2     1.3     <NA>    <NA>    SIL     <NA>    <NA>
SPEAKER mark.rttm       1       2.5     0.8     <NA>    <NA>    CHI     <NA>    <NA>
SPEAKER mark.rttm       1       3.3     1.1     <NA>    <NA>    FEM     <NA>    <NA>
SPEAKER mark.rttm       1       4.4     1.2     <NA>    <NA>    SIL     <NA>    <NA>
```

**Comment by alecristia** [comment] 2018-08-15 21:18
Excellent, thank you! We'll test it and report back if something goes awry.

**Closed by alecristia** 2018-08-15 21:18 UTC
